spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testDB
    username: postgres
    password: 123!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        query:
          plan_cache_max_size: 512